"""Render Prefect Cloud deployment artifacts (``prefect.yaml`` + ``DEPLOY.md``).

argo2prefect targets **Prefect Cloud**. A converted flow is just Python; to run
it on a schedule in a client's workspace it needs a *deployment*. This module
turns the :class:`~argo2prefect.generator.DeploymentPlan` objects emitted during
code generation into:

* a project-level ``prefect.yaml`` that ``prefect deploy`` reads, and
* a ``DEPLOY.md`` runbook that walks the client through login -> work pool ->
  deploy.

Design notes
------------
* The **account/workspace** a deployment lands in is decided entirely by
  ``prefect cloud login`` (it lives in the CLI profile as ``PREFECT_API_URL`` /
  ``PREFECT_API_KEY``), never in this file. So ``prefect.yaml`` stays portable.
* The default work pool is **Prefect Managed** (``prefect:managed``): Prefect
  hosts the compute, so the client runs no worker and no infrastructure. It is
  the fastest way to a first green run — but it has resource/time limits and
  cannot run Docker or ``kubectl``, so we loudly encourage switching to a pool
  that matches the workload once things work.
* A remote worker can only run code it can fetch. If ``--source-repo`` is given
  we emit a ``git_clone`` pull step; otherwise we fall back to a local working
  directory and flag (honestly) that Managed/serverless pools cannot use it.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from .generator import DeploymentPlan

MANAGED_POOL_TYPE = "prefect:managed"


@dataclass
class DeployOptions:
    """Inputs for rendering the Prefect Cloud deployment artifacts."""

    work_pool: str = "managed-pool"
    work_pool_type: str = MANAGED_POOL_TYPE
    source_repo: str | None = None
    # The generator runtime, carried through only to warn when it cannot run on
    # the chosen work pool (e.g. docker/kubernetes work on Managed compute).
    runtime: str = "docker"
    project_name: str = "argo-flows"
    # Runtime deps installed into Managed compute at run time.
    pip_packages: list[str] = field(default_factory=lambda: ["prefect-shell>=0.3"])

    @property
    def is_managed(self) -> bool:
        return self.work_pool_type == MANAGED_POOL_TYPE

    @property
    def runtime_needs_richer_pool(self) -> bool:
        """True when the runtime can't run on a Managed/serverless-Python pool."""
        return self.is_managed and self.runtime in ("docker", "kubernetes")


def _yaml_scalar(value: str) -> str:
    """A YAML scalar. JSON strings are valid YAML flow scalars, so reuse json."""
    return json.dumps(value)


def render_prefect_yaml(plans: list[DeploymentPlan], opts: DeployOptions) -> str:
    """Render a project-level ``prefect.yaml`` for the given deployment plans."""
    out: list[str] = []
    out += [
        "# Prefect deployment configuration generated by argo2prefect.",
        "#",
        "# Target: Prefect Cloud. The account + workspace these deployments land in",
        "# come from `prefect cloud login` (stored in your CLI profile) — never from",
        "# this file, so it stays safe to commit and share.",
        "#",
        "# Step-by-step runbook: see DEPLOY.md next to this file.",
        "",
        f"name: {_yaml_scalar(opts.project_name)}",
        "",
        "# --- How each run fetches your flow code before executing it ------------",
    ]
    if opts.source_repo:
        out += [
            "pull:",
            "  - prefect.deployments.steps.git_clone:",
            f"      repository: {_yaml_scalar(opts.source_repo)}",
        ]
    else:
        out += [
            "# TODO(argo2prefect): a Prefect Managed / serverless work pool runs OFF your",
            "#   machine and cannot read this local path. Before `prefect deploy`, either",
            "#   re-run conversion with --source-repo <git-url>, or push these flow files",
            "#   to a git repo / remote storage and point the pull step at it.",
            "pull:",
            "  - prefect.deployments.steps.set_working_directory:",
            '      directory: "."   # local worker only — replace for Managed/serverless',
        ]
    out += [
        "",
        "# --- Work pool ----------------------------------------------------------",
        "# Default: Prefect Managed (prefect:managed) — Prefect hosts the compute, so",
        "# you run NO worker and NO infrastructure. This is the fastest path to a first",
        "# successful run.",
        "#",
        "# RECOMMENDED NEXT STEP: once a run succeeds, switch each deployment below to a",
        "# work pool that matches the workload. Managed compute has CPU/memory/time",
        "# limits and cannot run Docker or kubectl. Better fits:",
        "#   * kubernetes pool (+ an in-cluster worker)          - closest to Argo",
        "#   * ecs:push / cloud-run:push / azure-container-instance:push - serverless",
        "#         containers, still no worker to host (needs a cloud-credentials block)",
        "#   * docker / process pool (+ a worker you run)        - simple self-hosted",
        "# Change work_pool.name below, create that pool (see DEPLOY.md), then redeploy.",
        "",
        "deployments:",
    ]
    for plan in plans:
        out += _render_deployment(plan, opts)
    return "\n".join(out).rstrip() + "\n"


def _render_deployment(plan: DeploymentPlan, opts: DeployOptions) -> list[str]:
    entrypoint = f"{plan.entrypoint_file or 'flow.py'}:{plan.flow_func}"
    lines = [
        f"  - name: {_yaml_scalar(plan.name)}",
        f"    entrypoint: {_yaml_scalar(entrypoint)}",
        "    work_pool:",
        f"      name: {_yaml_scalar(opts.work_pool)}",
    ]
    if opts.is_managed and opts.pip_packages:
        pkgs = ", ".join(_yaml_scalar(p) for p in opts.pip_packages)
        lines += [
            "      job_variables:",
            f"        pip_packages: [{pkgs}]   # Managed installs these at run time",
        ]
    if plan.schedule:
        lines += [
            "    schedules:",
            f"      - cron: {_yaml_scalar(plan.schedule)}",
        ]
        if plan.timezone:
            lines.append(f"        timezone: {_yaml_scalar(plan.timezone)}")
    if plan.parameters:
        lines.append("    parameters:")
        for key, value in plan.parameters.items():
            lines.append(f"      {_yaml_scalar(key)}: {_yaml_scalar(value)}")
    return lines


def render_deploy_md(plans: list[DeploymentPlan], opts: DeployOptions) -> str:
    """Render a step-by-step Prefect Cloud deployment runbook."""
    pool = opts.work_pool
    out: list[str] = []
    out += [
        "# Deploying your converted flows to Prefect Cloud",
        "",
        "These steps deploy every flow in this folder to your Prefect **Cloud**",
        "workspace. All you need is the Prefect CLI:",
        "",
        "```bash",
        'pip install "prefect>=3,<4"      # or: uv tool install prefect',
        "```",
        "",
        "## 1. Connect to your Prefect Cloud account",
        "",
        "```bash",
        "prefect cloud login -k <YOUR_API_KEY>",
        "```",
        "",
        "This selects the account + workspace all deployments below will land in and",
        "stores it in your CLI profile. To switch workspaces later:",
        "",
        "```bash",
        'prefect cloud workspace set --workspace "<account>/<workspace>"',
        "```",
        "",
        "## 2. Create the work pool (one time)",
        "",
        "```bash",
        f"prefect work-pool create {pool} --type {opts.work_pool_type}",
        "```",
    ]
    if opts.is_managed:
        out += [
            "",
            "`prefect:managed` means **Prefect runs the compute** — no worker, no",
            "infrastructure to stand up. Perfect for a first run.",
        ]
    else:
        out += [
            "",
            f"A `{opts.work_pool_type}` pool needs a worker/infrastructure — see the",
            "Prefect Cloud docs for that pool type.",
        ]
    out += [
        "",
        "## 3. Deploy",
        "",
        "```bash",
        "prefect deploy --all      # reads prefect.yaml",
        "```",
        "",
        "Your deployments now appear in the Prefect Cloud UI, each on its schedule.",
        "",
        "## After it works: pick the right work pool",
        "",
        "Prefect Managed is the fastest way to see runs, but it has CPU/memory/time",
        "limits and **cannot run Docker or kubectl**. For anything beyond light",
        "Python, replace it with a pool that matches your workload:",
        "",
        "- **Kubernetes** pool (+ an in-cluster worker) — closest to how Argo ran.",
        "- **ECS / Cloud Run / Azure Container Instances push** pool — serverless",
        "  containers, still no worker to host (needs a cloud-credentials block).",
        "- **Process / Docker** pool (+ a worker you run) — simple self-hosted.",
        "",
        "Edit `work_pool.name` in `prefect.yaml`, create the new pool, and re-run",
        "`prefect deploy --all`.",
        "",
        "## Before you deploy — checklist",
        "",
    ]
    # Code delivery.
    if opts.source_repo:
        out.append(f"- [x] Flow code is fetched from `{opts.source_repo}` (git_clone pull step).")
    else:
        out += [
            "- [ ] **Code delivery.** `prefect.yaml` currently points the worker at a",
            "  local directory, which a Managed/serverless pool cannot read. Re-run",
            "  conversion with `--source-repo <git-url>`, or push these files to git and",
            "  update the `pull:` step, before deploying.",
        ]
    # Runtime mismatch.
    if opts.runtime_needs_richer_pool:
        out += [
            "- [ ] **Runtime mismatch.** These flows were generated with `--runtime",
            f"  {opts.runtime}`, which needs Docker/kubectl and will **not** run on the",
            "  default Managed pool. Switch to a matching pool (see above) before this",
            "  will actually execute.",
        ]
    out += [
        "",
        "## Deployments in this project",
        "",
    ]
    for plan in plans:
        sched = f" — schedule `{plan.schedule}`" if plan.schedule else ""
        entry = f"{plan.entrypoint_file or 'flow.py'}:{plan.flow_func}"
        out.append(f"- **{plan.name}** (`{entry}`){sched}")
    return "\n".join(out).rstrip() + "\n"
