# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: nightly-backup (CronWorkflow)
Runtime: kubernetes
"""

from __future__ import annotations

import json
import os
import tempfile
import uuid
from prefect import flow, task
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {'database_url': 'postgres://user:pass@db:5432/app'}


@task(name="backup")
def backup(database_url: str = ""):
    """Argo template 'backup' (container)."""
    _job_name = "backup-" + uuid.uuid4().hex[:8]
    _env = [{"name": "DB_URL", "value": database_url}]
    _container = {
        "name": "main",
        "image": "postgres:16",
        "command": ["sh", "-c", "pg_dump \"$DB_URL\" > /backup/dump.sql && echo done"],
        "env": _env,
    }
    _manifest = {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"name": _job_name},
        "spec": {
            "backoffLimit": 0,
            "template": {"spec": {"restartPolicy": "Never", "containers": [_container]}},
        },
    }
    _fd, _path = tempfile.mkstemp(suffix=".json")
    with os.fdopen(_fd, "w") as _fh:
        json.dump(_manifest, _fh)
    try:
        ShellOperation(commands=[
            f"kubectl apply -f {_path}",
            f"kubectl wait --for=condition=complete --timeout=1h job/{_job_name}",
        ]).run()
        _out = ShellOperation(commands=[f"kubectl logs job/{_job_name}"]).run()
    finally:
        os.unlink(_path)
    return "\n".join(_out)

@flow(name="nightly-backup")
def nightly_backup_flow(database_url: str = "postgres://user:pass@db:5432/app"):
    """Entry point for Argo CronWorkflow 'nightly-backup'."""
    WORKFLOW_PARAMETERS.update({"database_url": database_url})
    return backup(database_url=database_url)


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        nightly_backup_flow.serve(name="nightly-backup", cron="0 2 * * *", timezone="America/New_York")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        nightly_backup_flow()
