# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "docker>=7"]
# ///
"""Prefect flows generated by argo2prefect.

Source: nightly-backup (CronWorkflow)
Runtime: docker
"""

from __future__ import annotations


import docker

from prefect import flow, task

WORKFLOW_PARAMETERS = {"database_url": "postgres://user:pass@db:5432/app"}


@task(name="backup")
def backup(database_url: str = ""):
    """Argo template 'backup' (container)."""
    _env = {"DB_URL": database_url}
    _client = docker.from_env()
    _out = _client.containers.run(
        "postgres:16",
        ["sh", "-c", 'pg_dump "$DB_URL" > /backup/dump.sql && echo done'],
        environment=_env,
        remove=True,
        stdout=True,
        stderr=True,
    )
    return _out.decode().rstrip("\n")


@flow(name="nightly-backup")
def nightly_backup_flow(database_url: str = "postgres://user:pass@db:5432/app"):
    """Entry point for Argo CronWorkflow 'nightly-backup'."""
    WORKFLOW_PARAMETERS.update({"database_url": database_url})
    return backup(database_url=database_url)


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        nightly_backup_flow.serve(
            name="nightly-backup", cron="0 2 * * *", timezone="America/New_York"
        )
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        nightly_backup_flow()
