# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: nightly-backup (CronWorkflow)
Runtime: docker
"""

from __future__ import annotations

import shlex
from prefect import flow, task
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {'database_url': 'postgres://user:pass@db:5432/app'}


@task(name="backup")
def backup(database_url: str = ""):
    """Argo template 'backup' (container)."""
    _env = {"DB_URL": database_url}
    _parts = ["docker", "run", "--rm"]
    for _k, _v in _env.items():
        _parts += ["-e", f"{_k}={_v}"]
    _parts += ["postgres:16", "sh", "-c", "pg_dump \"$DB_URL\" > /backup/dump.sql && echo done"]
    _out = ShellOperation(commands=[shlex.join(_parts)]).run()
    return "\n".join(_out)

@flow(name="nightly-backup")
def nightly_backup_flow(database_url: str = "postgres://user:pass@db:5432/app"):
    """Entry point for Argo CronWorkflow 'nightly-backup'."""
    WORKFLOW_PARAMETERS.update({"database_url": database_url})
    return backup(database_url=database_url)


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        nightly_backup_flow.serve(name="nightly-backup", cron="0 2 * * *", timezone="America/New_York")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        nightly_backup_flow()
