# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "docker>=7"]
# ///
"""Prefect flows generated by argo2prefect.

Source: dag-diamond (Workflow)
Runtime: docker
"""

from __future__ import annotations


import docker

from prefect import flow, task

WORKFLOW_PARAMETERS = {"greeting": "hello"}


@task(name="echo")
def echo(message: str = ""):
    """Argo template 'echo' (container)."""
    _env = {}
    _client = docker.from_env()
    _out = _client.containers.run(
        "alpine:3.18",
        ["echo", message],
        environment=_env,
        remove=True,
        stdout=True,
        stderr=True,
    )
    return _out.decode().rstrip("\n")


@flow(name="diamond")
def diamond():
    """Argo dag template 'diamond'."""
    # A -> template 'echo'
    a_fut = echo.submit(message=f"{WORKFLOW_PARAMETERS['greeting']} from A")
    # B -> template 'echo'
    b_fut = echo.submit(
        message=f"B saw: {a_fut.result()}", wait_for=[_f for _f in [a_fut] if _f is not None]
    )
    # C -> template 'echo'
    c_fut = echo.submit(message="C", wait_for=[_f for _f in [a_fut] if _f is not None])
    # D -> template 'echo'
    d_fut = echo.submit(message="D", wait_for=[_f for _f in [b_fut, c_fut] if _f is not None])
    return None


@flow(name="dag-diamond")
def dag_diamond_flow(greeting: str = "hello"):
    """Entry point for Argo Workflow 'dag-diamond'."""
    WORKFLOW_PARAMETERS.update({"greeting": greeting})
    return diamond()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        dag_diamond_flow.serve(name="dag-diamond")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        dag_diamond_flow()
