# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: dag-diamond (Workflow)
Runtime: docker
"""

from __future__ import annotations

import shlex
from prefect import flow, task
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {'greeting': 'hello'}


@task(name="echo")
def echo(message: str = ""):
    """Argo template 'echo' (container)."""
    _env = {}
    _parts = ["docker", "run", "--rm"]
    for _k, _v in _env.items():
        _parts += ["-e", f"{_k}={_v}"]
    _parts += ["alpine:3.18", "echo", message]
    _out = ShellOperation(commands=[shlex.join(_parts)]).run()
    return "\n".join(_out)

@flow(name="diamond")
def diamond():
    """Argo dag template 'diamond'."""
    # A -> template 'echo'
    a_fut = echo.submit(message=f"{WORKFLOW_PARAMETERS['greeting']} from A")
    # B -> template 'echo'
    b_fut = echo.submit(message=f"B saw: {a_fut.result()}", wait_for=[_f for _f in [a_fut] if _f is not None])
    # C -> template 'echo'
    c_fut = echo.submit(message="C", wait_for=[_f for _f in [a_fut] if _f is not None])
    # D -> template 'echo'
    d_fut = echo.submit(message="D", wait_for=[_f for _f in [b_fut, c_fut] if _f is not None])
    return None

@flow(name="dag-diamond")
def dag_diamond_flow(greeting: str = "hello"):
    """Entry point for Argo Workflow 'dag-diamond'."""
    WORKFLOW_PARAMETERS.update({"greeting": greeting})
    return diamond()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        dag_diamond_flow.serve(name="dag-diamond")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        dag_diamond_flow()
