# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "docker>=7"]
# ///
"""Prefect flows generated by argo2prefect.

Source: loops-map (Workflow)
Runtime: docker
"""

from __future__ import annotations


import docker

from prefect import flow, task, unmapped

WORKFLOW_PARAMETERS = {}


@task(name="echo")
def echo(fruit: str = ""):
    """Argo template 'echo' (container)."""
    _env = {}
    _client = docker.from_env()
    _out = _client.containers.run(
        "alpine",
        ["echo", f"processing {fruit}"],
        environment=_env,
        remove=True,
        stdout=True,
        stderr=True,
    )
    return _out.decode().rstrip("\n")


@flow(name="loop-map")
def loop_map():
    """Argo steps template 'loop-map'."""
    # process -> template 'echo'
    _items = ["apple", "banana", "cherry"]
    process_fut = echo.map(fruit=[_item for _item in _items])
    return None


@flow(name="loops-map")
def loops_map_flow():
    """Entry point for Argo Workflow 'loops-map'."""
    return loop_map()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        loops_map_flow.serve(name="loops-map")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        loops_map_flow()
