# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: loops-map (Workflow)
Runtime: docker
"""

from __future__ import annotations

import shlex
from prefect import flow, task, unmapped
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {}


@task(name="echo")
def echo(fruit: str = ""):
    """Argo template 'echo' (container)."""
    _env = {}
    _parts = ["docker", "run", "--rm"]
    for _k, _v in _env.items():
        _parts += ["-e", f"{_k}={_v}"]
    _parts += ["alpine", "echo", f"processing {fruit}"]
    _out = ShellOperation(commands=[shlex.join(_parts)]).run()
    return "\n".join(_out)

@flow(name="loop-map")
def loop_map():
    """Argo steps template 'loop-map'."""
    # process -> template 'echo'
    _items = ['apple', 'banana', 'cherry']
    process_fut = echo.map(fruit=[_item for _item in _items])
    return None

@flow(name="loops-map")
def loops_map_flow():
    """Entry point for Argo Workflow 'loops-map'."""
    return loop_map()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        loops_map_flow.serve(name="loops-map")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        loops_map_flow()
