# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: script-python (Workflow)
Runtime: docker
"""

from __future__ import annotations

import os
import shlex
import tempfile
from prefect import flow, task
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {}


import re as _re


def _render_argo(_text, _inputs=None):
    """Substitute Argo `{{inputs.parameters.*}}` / `{{workflow.parameters.*}}` placeholders."""
    _inputs = _inputs or {}

    def _sub(_m):
        _key = _m.group(1).strip()
        if _key.startswith("inputs.parameters."):
            return str(_inputs.get(_key[len("inputs.parameters."):], ""))
        if _key.startswith("workflow.parameters."):
            return str(WORKFLOW_PARAMETERS.get(_key[len("workflow.parameters."):], ""))
        return _m.group(0)

    return _re.sub(r"\{\{\s*(.*?)\s*\}\}", _sub, _text)


@task(name="gen-random")
def gen_random():
    """Argo template 'gen-random' (script)."""
    _script = _render_argo("import random\nprint(random.randint(1, 100))\n", {})
    _env = {}
    _fd, _path = tempfile.mkstemp(suffix=".py")
    with os.fdopen(_fd, "w") as _fh:
        _fh.write(_script)
    try:
        _parts = ["docker", "run", "--rm", "-i"]
        for _k, _v in _env.items():
            _parts += ["-e", f"{_k}={_v}"]
        _parts += ["python:3.11-slim", "python"]
        _cmd = shlex.join(_parts) + " < " + shlex.quote(_path)
        _out = ShellOperation(commands=[_cmd]).run()
    finally:
        os.unlink(_path)
    return "\n".join(_out)

@task(name="print-message")
def print_message(message: str = ""):
    """Argo template 'print-message' (script)."""
    _script = _render_argo("print(\"message: {{inputs.parameters.message}}\")\n", {"message": message})
    _env = {}
    _fd, _path = tempfile.mkstemp(suffix=".py")
    with os.fdopen(_fd, "w") as _fh:
        _fh.write(_script)
    try:
        _parts = ["docker", "run", "--rm", "-i"]
        for _k, _v in _env.items():
            _parts += ["-e", f"{_k}={_v}"]
        _parts += ["python:3.11-slim", "python"]
        _cmd = shlex.join(_parts) + " < " + shlex.quote(_path)
        _out = ShellOperation(commands=[_cmd]).run()
    finally:
        os.unlink(_path)
    return "\n".join(_out)

@flow(name="gen-and-print")
def gen_and_print():
    """Argo steps template 'gen-and-print'."""
    # generate -> template 'gen-random'
    generate_fut = gen_random.submit()
    # show -> template 'print-message'
    show_fut = print_message.submit(message=f"random number was {generate_fut.result()}", wait_for=[_f for _f in [generate_fut] if _f is not None])
    return None

@flow(name="script-python")
def script_python_flow():
    """Entry point for Argo Workflow 'script-python'."""
    return gen_and_print()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        script_python_flow.serve(name="script-python")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        script_python_flow()
