# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "docker>=7"]
# ///
"""Prefect flows generated by argo2prefect.

Source: script-python (Workflow)
Runtime: docker
"""

from __future__ import annotations


import docker

from prefect import flow, task

WORKFLOW_PARAMETERS = {}


import re as _re


def _render_argo(_text, _inputs=None):
    """Substitute Argo `{{inputs.parameters.*}}` / `{{workflow.parameters.*}}` placeholders."""
    _inputs = _inputs or {}

    def _sub(_m):
        _key = _m.group(1).strip()
        if _key.startswith("inputs.parameters."):
            return str(_inputs.get(_key[len("inputs.parameters.") :], ""))
        if _key.startswith("workflow.parameters."):
            return str(WORKFLOW_PARAMETERS.get(_key[len("workflow.parameters.") :], ""))
        return _m.group(0)

    return _re.sub(r"\{\{\s*(.*?)\s*\}\}", _sub, _text)


@task(name="gen-random")
def gen_random():
    """Argo template 'gen-random' (script)."""
    _script = _render_argo("import random\nprint(random.randint(1, 100))\n", {})
    _env = {}
    _client = docker.from_env()
    _out = _client.containers.run(
        "python:3.11-slim",
        ["python", "-c", _script],
        environment=_env,
        remove=True,
        stdout=True,
        stderr=True,
    )
    return _out.decode().rstrip("\n")


@task(name="print-message")
def print_message(message: str = ""):
    """Argo template 'print-message' (script)."""
    _script = _render_argo(
        'print("message: {{inputs.parameters.message}}")\n', {"message": message}
    )
    _env = {}
    _client = docker.from_env()
    _out = _client.containers.run(
        "python:3.11-slim",
        ["python", "-c", _script],
        environment=_env,
        remove=True,
        stdout=True,
        stderr=True,
    )
    return _out.decode().rstrip("\n")


@flow(name="gen-and-print")
def gen_and_print():
    """Argo steps template 'gen-and-print'."""
    # generate -> template 'gen-random'
    generate_fut = gen_random.submit()
    # show -> template 'print-message'
    show_fut = print_message.submit(
        message=f"random number was {generate_fut.result()}",
        wait_for=[_f for _f in [generate_fut] if _f is not None],
    )
    return None


@flow(name="script-python")
def script_python_flow():
    """Entry point for Argo Workflow 'script-python'."""
    return gen_and_print()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        script_python_flow.serve(name="script-python")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        script_python_flow()
