# /// script
# requires-python = ">=3.9"
# dependencies = ["prefect>=3,<4", "prefect-shell>=0.3"]
# ///
"""Prefect flows generated by argo2prefect.

Source: steps-hello (Workflow)
Runtime: docker
"""

from __future__ import annotations

import shlex
from prefect import flow, task
from prefect_shell import ShellOperation

WORKFLOW_PARAMETERS = {'name': 'world'}


@task(name="print-message")
def print_message(message: str = ""):
    """Argo template 'print-message' (container)."""
    _env = {}
    _parts = ["docker", "run", "--rm"]
    for _k, _v in _env.items():
        _parts += ["-e", f"{_k}={_v}"]
    _parts += ["busybox", "echo", message]
    _out = ShellOperation(commands=[shlex.join(_parts)]).run()
    return "\n".join(_out)

@flow(name="hello-hello-hello")
def hello_hello_hello():
    """Argo steps template 'hello-hello-hello'."""
    # hello1 -> template 'print-message'
    hello1_fut = print_message.submit(message=f"hello1: {WORKFLOW_PARAMETERS['name']}")
    # hello2a -> template 'print-message'
    hello2a_fut = print_message.submit(message="hello2a", wait_for=[_f for _f in [hello1_fut] if _f is not None])
    # hello2b -> template 'print-message'
    hello2b_fut = print_message.submit(message="hello2b", wait_for=[_f for _f in [hello1_fut] if _f is not None])
    return None

@flow(name="steps-hello")
def steps_hello_flow(name: str = "world"):
    """Entry point for Argo Workflow 'steps-hello'."""
    WORKFLOW_PARAMETERS.update({"name": name})
    return hello_hello_hello()


if __name__ == "__main__":
    import sys

    if "--serve" in sys.argv:
        steps_hello_flow.serve(name="steps-hello")
    else:
        # One-off local run with default parameters.
        # Pass --serve to deploy this flow on the schedule above instead.
        steps_hello_flow()
